### ISSUE TITLE
Error when do npm star

### ISSUE THREAD

**Issue by lyminster** [BeyondScheme/angular2-discussion-portal#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gulp' ]
2 info using npm@3.10.10
3 info using node@v7.2.1
4 verbose run-script [ 'pregulp', 'gulp', 'postgulp' ]
5 info lifecycle angular2-BeyondScheme@1.0.0~pregulp: angular2-BeyondScheme@1.0.0
6 silly lifecycle angular2-BeyondScheme@1.0.0~pregulp: no script for pregulp, continuing
7 info lifecycle angular2-BeyondScheme@1.0.0~gulp: angular2-BeyondScheme@1.0.0
8 verbose lifecycle angular2-BeyondScheme@1.0.0~gulp: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-BeyondScheme@1.0.0~gulp: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;d:\angular\MAP\PortalMaster\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;d:\angular\MAP\PortalMaster\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Users\Administrator\AppData\Roaming\npm\node_modules\angular-cli\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;;C:\Users\Administrator\AppData\Roaming\npm\node_modules\angular-cli\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\rommy.gautanto\AppData\Roaming\npm
10 verbose lifecycle angular2-BeyondScheme@1.0.0~gulp: CWD: d:\angular\MAP\PortalMaster
11 silly lifecycle angular2-BeyondScheme@1.0.0~gulp: Args: [ '/d /s /c', 'gulp' ]
12 silly lifecycle angular2-BeyondScheme@1.0.0~gulp: Returned: code: 1  signal: null
13 info lifecycle angular2-BeyondScheme@1.0.0~gulp: Failed to exec gulp script
14 verbose stack Error: angular2-BeyondScheme@1.0.0 gulp: `gulp`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular2-BeyondScheme@1.0.0
16 verbose cwd d:\angular\MAP\PortalMaster
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
19 error node v7.2.1
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular2-BeyondScheme@1.0.0 gulp: `gulp`
22 error Exit status 1
23 error Failed at the angular2-BeyondScheme@1.0.0 gulp script 'gulp'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-BeyondScheme package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-BeyondScheme
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-BeyondScheme
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

i have this kind of error,

did i do something wrong when installing?

**Comment by Tomabana** [comment]
Probably there is a problem with yours npm packages. Please follow these steps:
1) Delete your working directory with cloned repository.
2) Clone repository once again.
3) Run npm clean cache.
3) Run npm install and then npm start.

**Comment by Tomabana** [comment]
@lyminster Did you manage to run the project?
