### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by olagatta** [BeyondScheme/angular2-discussion-portal#2]
Hi Tomasz

aren't you creating an infinite loop subscribing once and again to refreshData()? 
Won't this make the page unresponsive ? and eventually to crash ?

**Comment by Tomabana** [comment]
Hi,
Angular uses rxjs which supports asynchronous operations.
Code `Observable.timer(5000).subscribe(() => this.refreshData());` means that after 5s `refreshData()` will be invoked. This operation is asynchronous, so we won't block any other operation while waiting for `timer` to generate event.
